### ISSUE TITLE
Abinitio outputs - Augustus

### ISSUE THREAD

**Issue by ViriatoII** [NBISweden/pipelines-nextflow#25]
Hi,

Your pipeline is working well.  I just don't understand what is the output of the Augustus part that I'm supposed to collect for maker and how. I have a good SNAP .hmm but here's what I see in the Augustus part:

```
guerrer@hilbert141:$ ll Augustus_training/test_species
test_species_exon_probs.pbl
test_species_igenic_probs.pbl
test_species_intron_probs.pbl
test_species_metapars.cfg
test_species_metapars.cgp.cfg
test_species_metapars.utr.cfg
test_species_parameters.cfg
test_species_weightmatrix.txt

```

**Comment by Juke34** [comment]
`test_species` folder has to be moved into the `augustus/config/species/` folder. It is a new hmm profile available among the other species standing in this folder (tomato, fly,etc...). Augustus will refer to it as `test_species`. If you modify the name, be careful to change the name of the folder and of all the files it contains. This must be consistent.

**Comment by ViriatoII** [comment]
That's it, thank you so much!

maker_opts.ctl:
```
#-----Gene Prediction
snaphmm=nextflow_abInitio/Snap_training/test_species.hmm
gmhmm= #GeneMark HMM file
augustus_species=test_species  <--- same name as folder in augustus_path/config/species/
```
