### ISSUE TITLE
PBS script not loading conda

### ISSUE THREAD

**Issue by ViriatoII** [NBISweden/pipelines-nextflow#29]
Hi,

The  .command.run that is generated in my scratch does not load conda and then fails to find it. 

```
/var/spool/pbs/mom_priv/jobs/5865502.hpc-batch14.SC: line 286: conda: command not found
/var/spool/pbs/mom_priv/jobs/5865502.hpc-batch14.SC: line 286: /bin/activate: No such file or directory
```

In PBS, conda is not in PATH unless its loaded, in my case it's :

module load  Miniconda/3   # but it might be different on other clusters

Is there a way of automatically integrating this in the .command.run file? Otherwise the solution is to put it in my .bashrc, I lost sometime before that occured to me.

**Comment by mahesh-panchal** [comment]
Hi @ViriatoII ,

There are several options available to you to resolve this if you've not been able to.
You can use the `module` directive in a custom config to do `module load Miniconda/3`.
There is also the `beforeScript` directive that lets you execute something before a script is run.

https://www.nextflow.io/docs/latest/process.html#module

I hope this solves your question.
Regards
