### ISSUE TITLE
Update AGAT to version 0.4.0

### ISSUE THREAD

**Issue by Juke34** [NBISweden/pipelines-nextflow#42]
AGAT can be updated. For each pipeline we need to change the version in:

 * label_agat.yml
 * software_packages.config
 
For pipeline using the script `agat_sp_split_by_level2_feature.pl` it must be replaced by `agat_sp_separate_by_record_type.pl`. (name changed in version > 0.2.3)

I don't know if any pipeline use `agat_sp_gxf_to_gff3.pl`  but is has been removed in new AGAT version (version > 0.2.3). It successor is `agat_convert_sp_gxf2gxf.pl`.

**Comment by royfrancis** [comment]
* agat version updated to 0.4.0
* *agat_sp_split_by_level2_feature.pl* replaced with *agat_sp_feature_by_record_type.pl*
* no instances of *agat_sp_gxf_to_gff3.pl* found.
Changes are on branch agat_0.4.0

#43
