### ISSUE TITLE
The problem with installation.

### ISSUE THREAD

**Issue by unavailable-2374** [NBISweden/pipelines-nextflow#77]
hello there, I want to use this beautiful tool for annotating my genome , but I can't install it.

could you please help me?

this is my log when I try to install it. 

'''
[caoshuo@login04 tools]$ curl -s https://get.nextflow.io | bash
/usr/bin/md5sum: 第 2 行:[: ==: 期待一元表达式
CAPSULE: Downloading dependency dev.failsafe:failsafe:jar:3.1.0
CAPSULE EXCEPTION: Error resolving dependencies. while processing attribute Allow-Snapshots: false (for stack trace, run with -Dcapsule.log=verbose)
Unable to initialize nextflow environment
'''

thanks!

best wishes.

**Comment by mahesh-panchal** [comment]
H, sorry for the delay. I was on holiday. 

I'm sorry, but I'm not sure exactly what the error is here. This is a question for the Nextflow developers https://github.com/nextflow-io/nextflow/issues. 
However, before making another issue, try one of their other [installation methods](https://www.nextflow.io/docs/latest/getstarted.html) such as
```bash
wget -qO- https://get.nextflow.io | bash
```
Or try installing via conda/mamba for example. 

I hope this helps.
