### ISSUE TITLE
"WARN: There's no process matching config selector" warning message

### ISSUE THREAD

**Issue by aersoares81** [NBISweden/pipelines-nextflow#78]
I'm getting this warning message:

```
[-        ] process > ANNOTATION_PREPROCESSING:AS... -
[-        ] process > ANNOTATION_PREPROCESSING:BUSCO -
Pulling Singularity image https://depot.galaxyproject.org/singularity/gaas:1.2.0--pl526r35_0 [cache /active/nxf_singularity_cachedir/depot.galaxyproject.org-singularity-gaas-1.2.0--pl526r35_0.img]
WARN: There's no process matching config selector: BLAST_BLASTN -- Did you mean: BLAST_BLASTP?
```
It doesn't look like it affects preprocessing, but I thought about bringing this up anyway.

**Comment by mahesh-panchal** [comment]
That's weird. Do you have a nextflow.config file in the same directory you're launching this pipeline from?

**Comment by mahesh-panchal** [comment]
There's no reference to `BLAST_BLASTN` in the workflow except in the README. I did find a small error with the blastp module but nothing to do with configuration like this.

**Comment by aersoares81** [comment]
It was a setting on the config file that was not needed for this.
